export const QUEUE_CONFIGS = {
  "email-send": {
    jobsPerMinute: 120,
    processingMs: { min: 100, max: 500 },
    baselineFailureRate: 0.01,
    workers: 3,
    concurrency: 5,
    retryAttempts: 3,
    jobNames: ["sendWelcomeEmail", "sendPasswordReset", "sendInvoice", "sendNotification"],
  },
  "webhook-deliver": {
    jobsPerMinute: 60,
    processingMs: { min: 50, max: 2000 },
    baselineFailureRate: 0.03,
    workers: 2,
    concurrency: 8,
    retryAttempts: 5,
    jobNames: ["deliverWebhook"],
  },
  "data-enrich": {
    jobsPerMinute: 10,
    processingMs: { min: 2000, max: 10000 },
    baselineFailureRate: 0.005,
    workers: 1,
    concurrency: 3,
    retryAttempts: 2,
    jobNames: ["enrichCompany", "enrichContact"],
  },
  "pdf-generate": {
    jobsPerMinute: 3,
    processingMs: { min: 5000, max: 30000 },
    baselineFailureRate: 0.02,
    workers: 1,
    concurrency: 1,
    retryAttempts: 1,
    jobNames: ["generateInvoicePdf", "generateReportPdf"],
  },
  "image-resize": {
    jobsPerMinute: 200,
    processingMs: { min: 100, max: 800 },
    baselineFailureRate: 0.005,
    workers: 2,
    concurrency: 10,
    retryAttempts: 2,
    jobNames: ["resizeAvatar", "resizeBanner"],
  },
  "payment-process": {
    jobsPerMinute: 20,
    processingMs: { min: 300, max: 1500 },
    baselineFailureRate: 0.01,
    workers: 2,
    concurrency: 3,
    retryAttempts: 5,
    jobNames: ["processCharge", "processRefund"],
  },
  "scheduled-cleanup": {
    jobsPerMinute: 5,
    processingMs: { min: 500, max: 2000 },
    baselineFailureRate: 0.01,
    workers: 1,
    concurrency: 2,
    retryAttempts: 1,
    jobNames: ["cleanExpiredSessions", "archiveOldRecords"],
    delayMs: { min: 5000, max: 30000 },
  },
  "report-monthly": {
    jobsPerMinute: 0,    // Idle until manually triggered
    processingMs: { min: 10000, max: 30000 },
    baselineFailureRate: 0,
    workers: 1,
    concurrency: 1,
    retryAttempts: 1,
    jobNames: ["generateMonthlyReport"],
  },
};
